# Generated by Django 6.1.1 on 2026-10-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='songs.album'),
        ),
    ]
