# Generated by Django 6.1.1 on 2026-10-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_remove_album_album_song_album_artistplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
