# Generated by Django 6.1.1 on 2026-10-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_artistfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='ml_track_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
