name: Deploy Music Platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 30m
          debug: true

          script: |
            echo "Connected to EC2"
            cd ~/Music_Platform
            git pull origin main
            docker compose down
            docker compose up -d --build
            docker compose ps
